cogs/rules.py, morpheushelper.py
added rule commands (fixes #9)
=> Rule commands

Pipfile, Pipfile.lock, cogs/mediaonly.py, cogs/reaction_pin.py, models/mediaonly_channel.py, morpheushelper.py
=> added mediaonly channels

cogs/invites.py, cogs/logging.py, models/allowed_invite.py, morpheushelper.py, util.py
added discord invite whitelist (fixes #10)
=> Invite whitelist

cogs/metaquestion.py, morpheushelper.py
=> added metafrage command

cogs/info.py, morpheushelper.py
=> added basic server info command

Dockerfile, Pipfile, Pipfile.lock, cogs/betheprofessional.py, cogs/info.py, cogs/invites.py, cogs/logging.py, cogs/mediaonly.py, cogs/metaquestion.py, cogs/reaction_pin.py, cogs/rules.py, cogs/voice_channel.py, database.py, docker-compose.yml, morpheushelper.py, multilock.py, util.py
added new features (fixes #21, #19 and #16)
=> Experimental

cogs/helpersystem.py, models/helper_roles.py, models/helper_scores.py, morpheushelper.py
=> Add helper score system with roles

.github/workflows/docker.yml
added caching for docker build
=> GitHub actions

cogs/codeblocks.py, morpheushelper.py
=> Add codeblocks cog with codeblocks command

cogs/voice_channel.py, translations/en.yml
As soon as a user is invited to a private talk, he will receive a link to the voice channel
=> As soon as a user is invited to a private talk, he will receive a link to the voice channel

Pipfile, cogs/discordpy_documentation.py, morpheushelper.py, translations/en.yml
Closes #85 
Looks like this now:
=> Add discordpy rtfm cog

Pipfile, Pipfile.lock, cogs/__init__.py, cogs/discordpy_documentation.py, translations/en.yml
=> Discordpy rtfm

morpheushelper/cogs/polls.py, translations/en.yml
New command (teampoll), checks, if all members voted.
=> added teampoll command

morpheushelper/cogs/metaquestion.py, morpheushelper/cogs/polls.py, morpheushelper/permissions.py, morpheushelper/util.py, translations/en.yml
Team members and the author of a poll can now delete the poll
=> Added wastebasket feature for polls

morpheushelper/cogs/voice_channel.py, translations/en.yml
=> .vc info command 

.github/dependabot.yaml
Added dependency updates
**Additional Notes**
SQUASH THE COMMITS
=> Added dependency updates

morpheushelper/cogs/polls.py, translations/en.yml
fixed emoji conversion in polls
fixed empty lines in polls
prevented user from using the same emoji more than once per poll
=> fixed poll commands

morpheushelper/cogs/__init__.py, morpheushelper/cogs/run_code.py, morpheushelper/emkc_api.py, translations/en.yml
In this commit a run command was added which allows to run code of any language using .run e.g. ```.run bash -ls -la```
=> RunCodeCog added

morpheushelper/cogs/rules.py, translations/en.yml
Added a function to cancel the sending or editing of a message the bot should send
=> Added cancel function for message sending/editing

morpheushelper/cogs/reddit.py
Adds an invisible character after every . and : in a reddit post title to prevent discord from recognizing it as a link
**Issue**
Closes #161
=> Workaround for reddit title link exploit

morpheushelper/cogs/reddit.py
Added parsing for html special characters in reddit post titles.
=> Added parsing for html special characters in reddit post titles

morpheushelper/cogs/__init__.py, morpheushelper/cogs/joined_info.py, translations/en.yml
In this commit a joined command was added, which returns the date on which a user joined a server
**Issue**
New Feature 
**Additional Notes**
Nothing to add
=> User joined cog added 

Dockerfile
=> Hopefully satisfy deepsource checks

morpheushelper/cogs/invites.py, morpheushelper/cogs/reddit.py, morpheushelper/cogs/voice_channel.py, morpheushelper/emkc_api.py, morpheushelper/morpheushelper.py
In this commit I have replaced the print statements with the Python logger
=> Removed print and added logger
